apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-peow
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:8325eb63d349409e9a53b53129ccf8cc28d5dc530e9f6787b2871941fcd30c2e
        name: my-nodejs
        resources: {}
status: {}
